# Generated by Django 5.1.7 on 2025-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=20)),
                ('drop', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('options', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=20)),
                ('ln', models.CharField(max_length=20)),
                ('em', models.EmailField(max_length=20)),
                ('gen', models.CharField(max_length=20)),
                ('un', models.CharField(max_length=20)),
                ('ps', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
