# Generated by Django 5.1.7 on 2025-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wloc_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=20)),
            ],
        ),
    ]
