# Generated by Django 5.1.7 on 2025-08-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0002_wloc_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='wloc_tbl',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bikeapp.reg_tbl'),
            preserve_default=False,
        ),
    ]
