# Generated by Django 5.1.7 on 2025-08-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_wloc_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tbl',
            name='pick',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wloc_tbl',
        ),
    ]
