# Generated by Django 5.1.7 on 2025-08-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0004_reg_tbl_pick_delete_wloc_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikenm', models.CharField(max_length=25)),
                ('bikeml', models.IntegerField()),
                ('bikeimg', models.FileField(upload_to='pic')),
            ],
        ),
    ]
