# Generated by Django 5.1.7 on 2025-08-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0005_bike_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike_tbl',
            old_name='bikeimg',
            new_name='bimg',
        ),
        migrations.RenameField(
            model_name='bike_tbl',
            old_name='bikeml',
            new_name='bml',
        ),
        migrations.RenameField(
            model_name='bike_tbl',
            old_name='bikenm',
            new_name='bnm',
        ),
    ]
