# Generated by Django 5.1.7 on 2025-08-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0006_rename_bikeimg_bike_tbl_bimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_tbl',
            name='worker',
            field=models.ForeignKey(default=1, limit_choices_to={'gen': 'worker'}, on_delete=django.db.models.deletion.CASCADE, to='bikeapp.reg_tbl'),
            preserve_default=False,
        ),
    ]
