# Generated by Django 5.1.7 on 2025-08-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0007_bike_tbl_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'gen': 'user'}, on_delete=django.db.models.deletion.CASCADE, to='bikeapp.reg_tbl')),
            ],
        ),
    ]
