# Generated by Django 5.1.7 on 2025-08-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0008_feed_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_tbl',
            name='name',
        ),
        migrations.AddField(
            model_name='pass_tbl',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_customer', to='bikeapp.reg_tbl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass_tbl',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_worker', to='bikeapp.reg_tbl'),
            preserve_default=False,
        ),
    ]
