# Generated by Django 5.1.7 on 2025-08-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0010_alter_pass_tbl_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_tbl',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'gen': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_worker', to='bikeapp.reg_tbl'),
        ),
    ]
